apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::516619614597:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BBHWW8Z62VN3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::516619614597:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::516619614597:user/Admin
      username: ops-user
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-02T06:17:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3287"
  uid: 5687b1b2-b425-42be-8fb5-d0076136ccf0
